### PR TITLE
Optionally include only test suites with the specified archiveId in the collection

### PR DESCRIPTION
**Pull request by rsandell**
Follow up to https://github.com/jenkinsci/junit-plugin/pull/27

@reviewbybees

### CODE REVIEW

**Comment by rsandell** [comment]
I'm going to rewrite this to use a separate field instead of the prefix hack

**Comment by rsandell** [comment]
Squashed the original commit into a new one with the changes to archiveId

**Comment by rsandell** [comment]
The error is because junit-plugin hasn't been released yet so SNAPSHOT dependency lookup fails.

**Comment by jglick** [comment]
As remarked upstream, I think this had better wait for a more comprehensive plan.

**Comment by dajose** [comment]
hey, I am looking for a functionality like this... Thing is I have multiple binary to execute my tests and having  all tests collected in the same bucket doesn't work for me.

Is there a plan to continue this PR or is there another path I could follow? @jglick

**Comment by jglick** [comment]
Discussion in https://github.com/jenkinsci/junit-plugin/pull/64. Needs to be thought out more carefully.

**Comment by rsandell** [comment]
Closing since there are other plans for this that I'm no longer involved with.

**Pull request closed without merging**
