### PR TITLE
Set up JEP-229

### PR DESCRIPTION
**Pull request by Vlatombe**
* Downstream of https://github.com/jenkins-infra/repository-permissions-updater/pull/2461

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Review by jglick — CHANGES_REQUESTED** [review]
You forgot to delete https://github.com/jenkinsci/parallel-test-executor-plugin/blob/750a9fa7f29999963b5ad3ebd5731d860bcfe659/.github/workflows/release-drafter.yml again.

**Comment by Vlatombe** [comment]
🤦

**Comment by Vlatombe** [comment]
fyi I'm considering writing `incrementals:cdify` that does this thing.

**Review by jglick — APPROVED** [review]

**Comment by jglick** [comment]
blocked by https://github.com/jenkins-infra/helpdesk/issues/2849

**Pull request merged**
